<?php declare(strict_types=1);

/**
 * Copyright (C) Brian Faust
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cline\Discovery\Console\Command\ConsoleCommand;

use Cline\Discovery\Attribute\Console\AsConsoleCommand;
use Cline\Discovery\Support\Discovery\Console\ConsoleCommandDiscovery;
use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;

use function config;
use function count;
use function sort;
use function sprintf;
use function var_export;

/**
 * @author Brian Faust <brian@cline.sh>
 */
#[AsConsoleCommand('console-commands:cache')]
final class CacheCommand extends Command
{
    protected $signature = 'console-commands:cache';

    protected $description = 'Discover console commands via #[AsConsoleCommand] and cache to bootstrap/cache/console-commands.php.';

    public function handle(Filesystem $files): int
    {
        $this->info('Discovering console commands...');
        $list = ConsoleCommandDiscovery::discover();
        sort($list);

        $dir = (string) config('discovery.paths.bootstrap_cache');

        if (!$files->exists($dir)) {
            $files->makeDirectory($dir, 0o755, true);
        }

        $path = (string) config('discovery.paths.console_commands');
        $export = var_export($list, true);
        $files->put($path, <<<PHP
<?php
// Auto-generated by console-commands:cache
return {$export};
PHP);

        $this->components->info('Console commands cached successfully.');
        $this->line(sprintf(' - %d commands', count($list)));

        return self::SUCCESS;
    }
}
