<?php declare(strict_types=1);

/**
 * Copyright (C) Brian Faust
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cline\Discovery\Console\Command\DomainEntity;

use Cline\Discovery\Attribute\Console\AsConsoleCommand;
use Cline\Discovery\Support\Discovery\Persistence\DomainEntityDiscovery;
use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;

use function config;
use function count;
use function ksort;
use function sprintf;
use function var_export;

/**
 * Cache map of Infrastructure models to Domain entities discovered via #[UseDomainEntity].
 *
 * @author Brian Faust <brian@cline.sh>
 */
#[AsConsoleCommand('domain-entities:cache')]
final class CacheCommand extends Command
{
    protected $signature = 'domain-entities:cache';

    protected $description = 'Discover #[UseDomainEntity] on models and cache map to bootstrap/cache/domain-entities.php.';

    public function handle(Filesystem $files): int
    {
        $this->info('Discovering domain entities on models...');
        $map = DomainEntityDiscovery::discover();

        $dir = (string) config('discovery.paths.bootstrap_cache');

        if (!$files->exists($dir)) {
            $files->makeDirectory($dir, 0o755, true);
        }

        $path = (string) config('discovery.paths.domain_entities');
        ksort($map);
        $export = var_export($map, true);
        $files->put($path, <<<PHP
<?php
// Auto-generated by domain-entities:cache
return {$export};
PHP);

        $this->components->info('Domain entities cached successfully.');
        $this->line(sprintf(' - %d model/entity mappings', count($map)));

        return self::SUCCESS;
    }
}
