<?php declare(strict_types=1);

/**
 * Copyright (C) Brian Faust
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cline\Discovery\Console\Command\EventSubscriber;

use Cline\Discovery\Attribute\Console\AsConsoleCommand;
use Cline\Discovery\Support\Discovery\Event\EventSubscriberDiscovery;
use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;

use function config;
use function count;
use function sort;
use function sprintf;
use function var_export;

/**
 * @author Brian Faust <brian@cline.sh>
 */
#[AsConsoleCommand('event-subscribers:cache')]
final class CacheCommand extends Command
{
    protected $signature = 'event-subscribers:cache';

    protected $description = 'Discover event subscribers via #[AsEventSubscriber] and cache to bootstrap/cache/event-subscribers.php';

    public function handle(Filesystem $files): int
    {
        $this->info('Discovering event subscribers...');
        $list = EventSubscriberDiscovery::discover();
        sort($list);

        $dir = (string) config('discovery.paths.bootstrap_cache');

        if (!$files->exists($dir)) {
            $files->makeDirectory($dir, 0o755, true);
        }

        $path = (string) config('discovery.paths.event_subscribers');
        $export = var_export($list, true);
        $files->put($path, <<<PHP
<?php
// Auto-generated by event-subscribers:cache
return {$export};
PHP);

        $this->components->info('Event subscribers cached successfully.');
        $this->line(sprintf(' - %d subscribers', count($list)));

        return self::SUCCESS;
    }
}
