<?php declare(strict_types=1);

/**
 * Copyright (C) Brian Faust
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cline\Discovery\Console\Command\LivewireComponent;

use Cline\Discovery\Attribute\Console\AsConsoleCommand;
use Cline\Discovery\Support\LivewireComponentDiscoveryInterface;
use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;

use function config;
use function count;
use function ksort;
use function sprintf;
use function var_export;

/**
 * @author Brian Faust <brian@cline.sh>
 */
#[AsConsoleCommand('livewire-components:cache')]
final class CacheCommand extends Command
{
    protected $signature = 'livewire-components:cache';

    protected $description = 'Discover Livewire components via #[AsLivewireComponent] and cache map to bootstrap/cache/livewire-components.php.';

    public function handle(Filesystem $files, LivewireComponentDiscoveryInterface $discovery): int
    {
        $this->info('Discovering Livewire components...');
        $map = $discovery->discover();
        ksort($map);

        $dir = (string) config('discovery.paths.bootstrap_cache');

        if (!$files->exists($dir)) {
            $files->makeDirectory($dir, 0o755, true);
        }

        $path = (string) config('discovery.paths.livewire_components');
        $export = var_export($map, true);
        $files->put($path, <<<PHP
<?php
// Auto-generated by livewire-components:cache
return {$export};
PHP);

        $this->components->info('Livewire components cached successfully.');
        $this->line(sprintf(' - %d components', count($map)));

        return self::SUCCESS;
    }
}
