<?php declare(strict_types=1);

/**
 * Copyright (C) Brian Faust
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cline\Discovery\Console\Command\Policy;

use Cline\Discovery\Attribute\Console\AsConsoleCommand;
use Cline\Discovery\Support\Discovery\Auth\PolicyDiscovery;
use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;

use function config;
use function count;
use function ksort;
use function sprintf;
use function var_export;

/**
 * @author Brian Faust <brian@cline.sh>
 */
#[AsConsoleCommand('policies:cache')]
final class CacheCommand extends Command
{
    protected $signature = 'policies:cache';

    protected $description = 'Discover policies via #[AsPolicy] and cache map to bootstrap/cache/policies.php.';

    public function handle(Filesystem $files): int
    {
        $this->info('Discovering policies...');
        $map = PolicyDiscovery::discover();

        $dir = (string) config('discovery.paths.bootstrap_cache');

        if (!$files->exists($dir)) {
            $files->makeDirectory($dir, 0o755, true);
        }

        $path = (string) config('discovery.paths.policies');
        ksort($map);
        $export = var_export($map, true);
        $files->put($path, <<<PHP
<?php
// Auto-generated by policies:cache
return {$export};
PHP);

        $this->components->info('Policies cached successfully.');
        $this->line(sprintf(' - %d policies', count($map)));

        return self::SUCCESS;
    }
}
