<?php declare(strict_types=1);

/**
 * Copyright (C) Brian Faust
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    /*
    |--------------------------------------------------------------------------
    | Discovery Cache Paths
    |--------------------------------------------------------------------------
    |
    | Central location for all cache files written by discovery commands and
    | providers. Adjust these if deploying with a non-standard filesystem
    | layout such as an ephemeral boot cache directory.
    |
    */
    'paths' => [
        /*
        |--------------------------------------------------------------------------
        | Base Cache Directory
        |--------------------------------------------------------------------------
        |
        | Absolute directory under which all discovery artifacts are persisted.
        | Commands will create this directory if it does not exist. In platform
        | environments with ephemeral filesystems (e.g., Vapor), override this
        | to a writable path such as "/tmp/storage/bootstrap/cache" to ensure
        | caches can be generated at boot and used across the request lifecycle.
        */
        'bootstrap_cache' => base_path('bootstrap/cache'),
        /*
        |--------------------------------------------------------------------------
        | Command Handlers Map
        |--------------------------------------------------------------------------
        |
        | Path to the generated associative array mapping command classes to
        | their handler classes, produced by the "handlers:cache" command.
        | Consumed at boot by the BusServiceProvider to register the map with
        | Laravel’s dispatcher, avoiding runtime reflection in production.
        */
        'command_handlers' => base_path('bootstrap/cache/command-handlers.php'),
        /*
        |--------------------------------------------------------------------------
        | Query Handlers Map
        |--------------------------------------------------------------------------
        |
        | Path to the generated associative array mapping query classes to
        | their handler classes, produced by the "handlers:cache" command.
        | Loaded by the BusServiceProvider alongside command handlers to enable
        | fast query dispatch without discovery in production environments.
        */
        'query_handlers' => base_path('bootstrap/cache/query-handlers.php'),
        /*
        |--------------------------------------------------------------------------
        | Event Listeners Map
        |--------------------------------------------------------------------------
        |
        | Path to the generated associative array mapping event classes to a
        | list of listener class or "Class@method" strings, created by the
        | "handlers:cache" discovery. Loaded by EventListenerServiceProvider to
        | register listeners without scanning attributes during application boot.
        */
        'event_handlers' => base_path('bootstrap/cache/event-handlers.php'),
        /*
        |--------------------------------------------------------------------------
        | Console Commands
        |--------------------------------------------------------------------------
        |
        | Path to a generated list of console command class names discovered via
        | attributes and cached by the "console-commands:cache" command. Used by
        | ConsoleDiscoveryServiceProvider to register commands quickly when the
        | application is running in console mode without reflective discovery.
        |
        */
        'console_commands' => base_path('bootstrap/cache/console-commands.php'),
        /*
        |--------------------------------------------------------------------------
        | Authorization Policies
        |--------------------------------------------------------------------------
        |
        | Path to an associative array mapping Eloquent model classes to policy
        | classes, generated by "policies:cache". Consumed by PolicyServiceProvider
        | to register policies on the Gate at boot for consistent authorization.
        |
        */
        'policies' => base_path('bootstrap/cache/policies.php'),
        /*
        |--------------------------------------------------------------------------
        | Event Subscribers List
        |--------------------------------------------------------------------------
        |
        | Path to a generated list of event subscriber class names produced by
        | the "event-subscribers:cache" command. Loaded by the
        | EventSubscriberServiceProvider to subscribe classes to the dispatcher
        | without scanning attributes in production.
        */
        'event_subscribers' => base_path('bootstrap/cache/event-subscribers.php'),
        /*
        |--------------------------------------------------------------------------
        | Livewire Components Map
        |--------------------------------------------------------------------------
        |
        | Path to an associative array mapping Livewire component aliases to
        | their component classes. Generated by the "livewire-components:cache"
        | command and consumed by LivewireAutoDiscoveryServiceProvider to
        | register components efficiently during application boot.
        */
        'livewire_components' => base_path('bootstrap/cache/livewire-components.php'),
        /*
        |--------------------------------------------------------------------------
        | Domain Entities Map
        |--------------------------------------------------------------------------
        |
        | Path to an associative array mapping Infrastructure model classes to
        | their corresponding Domain entity classes. Generated by
        | "domain-entities:cache" and loaded by ModelEntityRegistry to support
        | consistent model ↔ entity lookups across bounded contexts.
        */
        'domain_entities' => base_path('bootstrap/cache/domain-entities.php'),
        /*
        |--------------------------------------------------------------------------
        | Context Attributes Map
        |--------------------------------------------------------------------------
        |
        | Path to an associative array used by the bus middleware to apply or
        | clear Business Unit context for messages. The array has the shape:
        |   [
        |     'with'    => array<class-string, non-empty-string>, // message => id property
        |     'cleared' => array<class-string, true>,             // messages that clear context
        |   ]
        | and is generated by the "context-attributes:cache" command.
        */
        'context_attributes' => base_path('bootstrap/cache/context-attributes.php'),
        /*
        |--------------------------------------------------------------------------
        | JSON-RPC Resources
        |--------------------------------------------------------------------------
        |
        | Path to an associative array mapping Eloquent model classes to their
        | JSON-RPC resource classes. Generated by the resources discovery cache
        | command and loaded by the JsonRpcServiceProvider to register RPC
        | resource bindings without reflection in production.
        |
        */
        'json_rpc_resources' => base_path('bootstrap/cache/json-rpc-resources.php'),
    ],
];
