<?php declare(strict_types=1);

/**
 * Copyright (C) Brian Faust
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cline\Discovery\Console\Command\Handler;

use Cline\Discovery\Attribute\Console\AsConsoleCommand;
use Cline\Discovery\Support\Bus\Discovery\HandlerDiscovery;
use Cline\Discovery\Support\Discovery\Event\EventListenerDiscovery;
use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;

use function array_map;
use function array_sum;
use function config;
use function count;
use function ksort;
use function sprintf;
use function var_export;

/**
 * @author Brian Faust <brian@cline.sh>
 */
#[AsConsoleCommand('handlers:cache')]
final class CacheCommand extends Command
{
    protected $signature = 'handlers:cache';

    protected $description = 'Discover command/query/event handlers and cache maps to bootstrap/cache.';

    public function handle(Filesystem $files): int
    {
        $this->info('Discovering handlers...');

        $maps = HandlerDiscovery::discover();
        $events = EventListenerDiscovery::discover();

        $cacheDir = (string) config('discovery.paths.bootstrap_cache');

        if (!$files->exists($cacheDir)) {
            $files->makeDirectory($cacheDir, 0o755, true);
        }

        $commandsFile = (string) config('discovery.paths.command_handlers');
        $queriesFile = (string) config('discovery.paths.query_handlers');
        $eventsFile = (string) config('discovery.paths.event_handlers');

        self::writeArrayFile($files, $commandsFile, $maps['commands']);
        self::writeArrayFile($files, $queriesFile, $maps['queries']);
        self::writeArrayFile($files, $eventsFile, $events);

        $this->components->info('Handlers cached successfully.');
        $this->line(sprintf(' - %s commands', count($maps['commands'])));
        $this->line(sprintf(' - %s queries', count($maps['queries'])));
        $this->line(sprintf(' - %s events, %s listeners', count($events), array_sum(array_map('count', $events))));

        return self::SUCCESS;
    }

    /**
     * @param array<mixed, mixed> $map
     */
    private static function writeArrayFile(Filesystem $files, string $path, array $map): void
    {
        ksort($map);
        $export = var_export($map, true);
        $content = <<<PHP
<?php
// This file is auto-generated by handlers:cache
return {$export};
PHP;
        $files->put($path, $content);
    }
}
